CREATE TABLE invoice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name VARCHAR(255),
    source_email VARCHAR(255),
    file_path VARCHAR(255),
    status VARCHAR(50),
    created_at TIMESTAMP
);
